services:
  booking-app:
    build: .
    container_name: booking-app
    volumes:
      - .:/var/www
      - booking_vendor:/var/www/vendor
    networks:
      - laravel-net
    depends_on:
      booking-db:
        condition: service_healthy

  booking-nginx:
    image: nginx:stable-alpine
    container_name: booking-nginx
    ports:
      - "8003:80"
    volumes:
      - .:/var/www
      - booking_vendor:/var/www/vendor
      - ../nginx/booking.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-net
    depends_on:
      - booking-app

  booking-db:
    image: mysql:8
    container_name: booking-db
    environment:
      MYSQL_DATABASE: bookings
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3309:3306"
    volumes:
      - booking_db_data:/var/lib/mysql
    networks:
      - laravel-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-psecret"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  laravel-net:
    external: true

volumes:
  booking_db_data:
  booking_vendor:
